
name: NestJs Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  API_KEY: ${{ secrets.API_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm ci
      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start
          echo "CREATE DATABASE test_db" | mysql -u root -p${{ secrets.DB_PASSWORD }}
      - name: Run Unit tests
        run: npm run test
      - name: Run E2E tests
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USERNAME: root
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: npm run test:e2e