name: NestJs Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  API_KEY: ${{ secrets.API_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm run test